-- require("fhof.lsp-config")
require("fhof.treesitter")
require("fhof.telescope")
require("fhof.nvim-cmp")
require("fhof.lspkind")
require("fhof.devicons")
require("fhof.autopairs")
require("fhof.todo")
require("fhof.which-key")
require("fhof.colorizer")
require("fhof.comment")
