[theme]
name = "modern"
[theme.overrides]
idle_bg = "#EEEEEE"
idle_fg = "#0D0D0D"

[icons]
name = "awesome"
[icons.overrides]
time = ""
backlight_empty = " "
backlight_partial1 = " "
backlight_partial2 = " "
backlight_partial3 = " "
backlight_full = " "

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "{icon} {used}/{total} ({available} free)"
alert_absolute = true
unit = "GB"
alert = 400
warning = 450

#[[block]]
#block = "weather"
#format = "{temp}°C {weather}, {wind}m/s {direction}"
#service = { name = "openweathermap", api_key = "82b3c5fede9070e99419dde454a2db96", city_id = "5969785", units = "metric" }

[[block]]
block = "net"
device = "wlo1"
format = "{ssid} {signal_strength} {speed_down;K*b}"
interval = 5

#[[block]]
#block = "net"
#device = "enp0s31f6"
#ip = true
#speed_up = false
#speed_down = true
#interval = 5

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 5
format = "{utilization} {frequency}"

[[block]]
block = "sound"
show_volume_when_muted = true

#[[block]]
#block = "backlight"
#
[[block]]
block = "battery"
interval = 10
format = "{percentage} {time} {power}"

[[block]]
block = "time"
interval = 60
format = " %a %b %d,%l:%M%p"

