[theme]
name = "modern"
[theme.overrides]
idle_bg = "#EEEEEE"
idle_fg = "#0D0D0D"
separator= ""

[icons]
name = "awesome"
[icons.overrides]
time = ""
backlight_empty = " "
backlight_partial1 = " "
backlight_partial2 = " "
backlight_partial3 = " "
backlight_full = " "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0
format = "root: $available.eng(2)"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "$mem_total_used_percents.eng(2)"
format_swap = "$swap_used_percents.eng(2)"

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "sound"
show_volume_when_muted = true

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time} {power}"

[[block]]
block = "time"
interval = 60
format = " %a %b %d,%l:%M%p"

