#!/usr/bin/env bash


NOTEBOOK_MON="eDP-1"
MID_MON="DVI-I-3-2"
LEFT_MON="DVI-I-2-1"

MID_MON_ARGS="--mode 3840x2160 --scale 1x1 --pos 0x0"
LEFT_MON_ARGS="--mode 3840x2160 --scale 1x1 --pos 3840x0 --primary"

leftmon_args_work="--mode 2560x1440 --scale 1x1 --pos 0x0"
midmon_args_work="--mode 2560x1440 --scale 1x1 --pos 2560x0 --primary"
