#!/usr/bin/env bash

LEFT_MON_ARGS="--mode 3840x2160 --scale 1x1 --pos 0x0 --primary"
RIGHT_MON_ARGS="--mode 3840x2160 --scale 1x1 --pos 3840x0"

leftmon_args_work="--mode 2560x1440 --scale 1x1 --pos 0x0 --primary"
rightmon_args_work="--mode 2560x1440 --scale 1x1 --pos 2560x0"

# Replace these with unique patterns from your monitors' EDIDs
# Find them with: xrandr --prop | grep -A 10 "EDID:"
LAPTOP_EDID_PATTER="00ffffffffffff000e6f031600000000"
LEFT_EDID_PATTERN="00ffffffffffff0010ac96a14c4f4331"
RIGHT_EDID_PATTERN="00ffffffffffff0010ac97a14c413031"
