add_newline = false

palette = "catppuccin_latte"

# Order of modules on prompt
format = """\
        $time\
        $directory\
        $git_branch\
        $git_status\
        $python\
        \n$status\
        $character\
    """

# Generic prompt configurations
[character]
success_symbol = "[](fg:green)"
error_symbol = "[[](bg:#ff3322 fg:#3a3a3a)](fg:#ff3322)"
format = "[[](bg:#3a3a3a)$symbol]($style)"
# success_symbol = "[](green)"
# error_symbol = "[❯](red)"
# vimcmd_symbol = "[❮](green)"

[time]
disabled = false
style = "bg:mauve fg:base"
format = '[$time]($style)'
time_format = '%m/%d/%R'
utc_time_offset = '-5'

[line_break]
disabled = true

[directory]
style = "italic bg:#3a3a3a fg:#dadada"
truncation_length = 3
truncation_symbol = "/"
# fish_style_pwd_dir_length = 1
format = "([[](bg:#3a3a3a fg:#3a3a3a)]($read_only_style))[[](bg:#3a3a3a fg:mauve)$path[](bg:#008700 fg:#3a3a3a)]($style)"

[directory.substitutions]
"~/Downloads" = " "
"~/projects" = " "
"~" = " "

[git_branch]
symbol = ""
style = "bg:#008700 fg:#dadada"
# truncation_length = 4
# truncation_symbol = ""
format = "[$symbol$branch[](bg:pink fg:#008700)]($style)"

[git_status]
style = "bg:pink fg:text"
stashed = "${count}"
ahead = "ﲗ${count}"
behind = "↡ ${count}"
diverged = "↔ ${ahead_count} ${behind_count}"
conflicted = "≠${count}"
deleted = "${count}"
renamed = "r${count}"
modified = "${count}"
staged = "⎆ ${count}"
untracked = "⇪ ${count}"
format = "([(bg:text fg:pink)$all_status[](fg:pink)]($style))"

[status]
disabled = false
symbol = ""
style = "bg:#3a3a3a fg:#ff3322"
format = "[$symbol$status]($style)"

# [python]
# # Display the version of python from inside a local venv.
# #
# # Note this will only work when the venv is inside the project and it will only
# # work in the directory that contains the venv dir but maybe this is ok?
# python_binary = ["./venv/bin/python", "python3", "python", "python2"]
# symbol =""

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
# mauve = "#8839ef"
mauve = "#af00af"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#EEEEEE"
mantle = "#e6e9ef"
crust = "#dce0e8"

[python]
python_binary = ".venv/bin/python"
symbol =""

[custom.uv-version]
description = "The currently installed version of uv"
shell = "bash"
detect_files = [
  ".python-version",
  "Pipfile",
  "__init__.py",
  "pylock.toml",
  "pyproject.toml",
  "requirements.txt",
  "setup.py",
  "tox.ini",
  "uv.lock",
]
style = "bold fg:#dffe7c"
symbol = "by"
command = '''
if ! command -v uv >/dev/null; then
  exit 1
fi

uv_version=$(uv --version | awk '{print $2}')

emoji=⚡️
printf "%s v%s"     "$emoji" "$uv_version"
'''
format = "$symbol [($output )]($style)"

[custom.uv-lock]
description = "Symbol representing the state of the lock file"
shell = "bash"
style = "bold fg:#cf67e2"
detect_files = [
  ".python-version",
  "Pipfile",
  "__init__.py",
  "pylock.toml",
  "pyproject.toml",
  "requirements.txt",
  "setup.py",
  "tox.ini",
  "uv.lock",
]
command = '''
if ! command -v uv >/dev/null; then
  exit 1
fi

suffix=""
if uv lock --check-exists >/dev/null; test $? -eq 2; then
  suffix="?"
elif uv lock --check >/dev/null; test $? -eq 2; then
  suffix="!"
fi

if [ -n "$suffix" ]; then
  printf ["$suffix"]
fi
'''
format = "[($output )]($style)"
