#!/bin/sh

NOTES_LOCATION="/Notes/work/"
FORMATTED_DATE=$(date +%y-%m-%d)
FORMATTED_MONTH=$(date +%y_%m)
DIR_NAME="$HOME$NOTES_LOCATION$FORMATTED_MONTH"

if [ ! -d $DIR_NAME ]; then
    mkdir -p $DIR_NAME
fi

FILENAME="$HOME$NOTES_LOCATION$FORMATTED_MONTH/$FORMATTED_DATE.md"

if [ ! -f $FILENAME ]; then
  echo "# Notes for $FORMATTED_DATE" >> $FILENAME
  echo "## Pomodoro" >> $FILENAME
  echo "\`\`\`" >> $FILENAME
  echo "     1h2h3h4h5h6h7h8h" >> $FILENAME
  echo "    [                ]" >> $FILENAME
  echo "\`\`\`" >> $FILENAME
  echo "" >> $FILENAME
  echo "## Tasks" >> $FILENAME
  echo "- " >> $FILENAME
fi

nvim -c "norm Go" \
  -c "norm Go## $(date +%H:%M)" \
  -c "norm G2o" \
  -c "norm zz" \
  -c "startinsert" $FILENAME
